<a href="https://colab.research.google.com/github/acrismail/keras1_customerloss/blob/main/Keras1sadievren.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [62]:
#müşteri kayıp analizi yapıyoruz;

In [43]:
df=pd.read_csv("/content/churn.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [44]:
# müşteri kaybı için

In [45]:
X= df.iloc[:,3:13].values
Y = df.iloc[:,13].values

In [46]:
#encoder: Kategorik -> Numeric
from sklearn.preprocessing import LabelEncoder

le =LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

X[:,2] = le.fit_transform(X[:,2])

In [47]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])],
                        remainder="passthrough"
)

In [50]:

X = ohe.fit_transform(X)
X = X[:,1:]

In [52]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [54]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

In [55]:
x_train, x_test,y_train,y_test = train_test_split(X,Y,test_size=0.33, random_state=0)

In [56]:
#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

In [57]:
sc=StandardScaler()

In [58]:
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [61]:
#3 Yapay Sinir ağı


import keras
from keras.models import Sequential
from keras.layers import Dense

In [68]:
classifier=Sequential()   #model nesnesi oluşturularak,nesnee eklme,düzeltmeler yapılarak ysa oluşturulur

#kaç noron olacağı (11 bağımsız değ.,1 bağımlı değişken var) tartışmakonusu,ikisinin ortalaması olabilir (6),input_dım girişte kaç katman olacağı (11 )

#gizli katman ekleyelim(2 gizli katman oluşturduk)
classifier.add(Dense(6, activation = 'relu' , input_dim = 11))
classifier.add(Dense(6, activation = 'relu'))

#çıkış katmanındasigmoid olacak aktivasyon(1 noron)
classifier.add(Dense(1, activation = 'sigmoid'))


In [69]:
  #1-0 dan oluştuğu için binary(loss),fazla seçenek olsaydı(1 den fazla grup olsa categoric)
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [70]:
classifier.fit(X_train,y_train,epochs=50) #tur sayısı 50 seçtik (çok fazla seçilirse overfitting e yol açabilir)

Epoch 1/50
210/210 [==============================] - 2s 2ms/step - loss: 0.5185 - accuracy: 0.7984
Epoch 2/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4632 - accuracy: 0.7982
Epoch 3/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4455 - accuracy: 0.7985
Epoch 4/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.7982
Epoch 5/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4324 - accuracy: 0.8013
Epoch 6/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4288 - accuracy: 0.8088
Epoch 7/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4267 - accuracy: 0.8133
Epoch 8/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4245 - accuracy: 0.8152
Epoch 9/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8179
Epoch 10/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4212 - accuracy: 0.8187

In [71]:
y_pred=classifier.predict(X_test)

104/104 [==============================] - 0s 2ms/step


In [72]:
y_pred

array([[0.30840704],
       [0.32694244],
       [0.14214067],
       ...,
       [0.25609314],
       [0.6357177 ],
       [0.04866835]], dtype=float32)

In [73]:
#0.5 ten büyük olanlar bırakmasın,değilse bıraksın;

In [75]:
y_pred=(y_pred>0.5)

In [79]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [77]:
cm=confusion_matrix(y_test,y_pred)

In [78]:
cm

array([[2513,  104],
       [ 361,  322]])

In [81]:
# 2513+322 değeri doğru tahmin etmiş,başarı oranı yaklaşık olarak %86

In [82]:
accuracy_score(y_test,y_pred)

0.8590909090909091